
server {
    # Écoute sur le port 80 (HTTP standard)
    listen 80;
   
    # Nom du serveur (domaine accepté)
    server_name localhost;
    
    # ===================================
    # ROUTE POUR L'API LARAVEL
    # ===================================
    # Toutes les URLs commençant par /api/ seront traitées ici
    location /api/ {
        # Redirige la requête vers le conteneur Laravel sur le port 80 (Apache)
        proxy_pass http://api:80/;
       
        # Conserve le nom d'hôte original dans la requête
        proxy_set_header Host $host;
       
        # Transmet l'adresse IP réelle du client (pas celle de Nginx)
        proxy_set_header X-Real-IP $remote_addr;
       
        # Ajoute l'IP du client à la chaîne des proxies
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       
        # Indique le protocole utilisé (http ou https)
        proxy_set_header X-Forwarded-Proto $scheme;

    }
    
     # ===================================
    # ROUTE POUR L'ADMIN LARAVEL
    # ===================================
    # Toutes les URLs commençant par /api/ seront traitées ici
     location /admin/ {
        # Redirige la requête vers le conteneur Laravel sur le port 80 (Apache)
        proxy_pass http://admin:80/;
       
        # Conserve le nom d'hôte original dans la requête
        proxy_set_header Host $host;
       
        # Transmet l'adresse IP réelle du client (pas celle de Nginx)
        proxy_set_header X-Real-IP $remote_addr;
       
        # Ajoute l'IP du client à la chaîne des proxies
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       
        # Indique le protocole utilisé (http ou https)
        proxy_set_header X-Forwarded-Proto $scheme;

    }

    # ===================================
    # ROUTE POUR L'APPLICATION REACT
    # ===================================
    # Toutes les autres URLs (/) seront traitées ici
    # location / {
    #     # Redirige vers le conteneur React sur le port 5173
    #     proxy_pass http://react-app:5173;
       
    #     # Conserve le nom d'hôte original
    #     proxy_set_header Host $host;
       
    #     # Transmet l'IP réelle du client
    #     proxy_set_header X-Real-IP $remote_addr;
       
    #     # Chaîne des proxies pour traçabilité
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       
    #     # Protocole utilisé (important pour HTTPS)
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }
}